### ISSUE TITLE
Negative ID

### ISSUE THREAD

**Issue by iamMHZ** [nshafer/django-hashid-field#86]
Does it work on negative Id (integer)?

```
from hashid_field import Hashid 
h = Hashid(-123)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "venv/lib/python3.10/site-packages/hashid_field/hashid.py", line 73, in __init__
    raise ValueError("value must be a positive integer")
ValueError: value must be a positive integer
```

Is it possible to do some customization and make it happen?

**Comment by nshafer** [comment]
No, the hashids algorithm only supports positive unsigned integers.
